export const theme = {
  colors: {
    primary: '#2E7D32',
    primaryDark: '#1B5E20',
    primaryLight: '#4CAF50',
    secondary: '#FF6B35',
    accent: '#FF4081',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    error: '#D32F2F',
    text: '#212121',
    textSecondary: '#757575',
    white: '#FFFFFF',
    success: '#4CAF50',
    warning: '#FF9800',
    info: '#2196F3',
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#212121',
      lineHeight: 38,
    },
    h2: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#212121',
      lineHeight: 34,
    },
    h3: {
      fontSize: 22,
      fontWeight: '600',
      color: '#212121',
      lineHeight: 28,
    },
    body: {
      fontSize: 16,
      color: '#212121',
      lineHeight: 22,
    },
    caption: {
      fontSize: 14,
      color: '#757575',
      lineHeight: 18,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 16,
    },
  },
};